### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [noteed/riscv-hello-asm#6]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by noteed** [comment]
Hi,

Here you are: https://github.com/noteed/riscv-hello-asm/commit/87e051cfe8010b0eb9b1307dd1ba53ec8b41a7e0

**Comment by vazhnov** [comment]
@noteed , thank you!
Is it BSD 3-clause? By some reason, GitHub can't recognise it.

**Comment by noteed** [comment]
Yes, I've noticed. GitHub can't recognise this one either : https://github.com/michaeljclark/riscv-probe/blob/master/LICENSE.

But yes it's a BSD3. I copy pasted it from an older project of mine and I only use BSD3 or more recently BSD2.
